// tailwind.config.js
const colors = require("tailwindcss/colors");

module.exports = {
  important: "#app",
  purge: false,
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {},
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: colors.black,
      white: colors.white,
      gray: colors.coolGray,
      red: colors.red,
      green: colors.green,
      blue: colors.blue,
      indigo: colors.indigo,
    },
    fontFamily: {
      "helvetica-100": [
        '"Helvetica Neue W20_45 Light"',
        "Helvetica",
        "sans-serif",
      ],
      "helvetica-400": [
        '"Helvetica Neue W20_55 Roman"',
        "Helvetica",
        "sans-serif",
      ],
      "helvetica-700": [
        '"Helvetica Neue W20_75 Bold"',
        "Helvetica",
        "sans-serif",
      ],
      "museo-100": ['"Museo Sans W01_100"', "sans-serif"],
      "museo-300": ['"Museo Sans W01_300"', "sans-serif"],
      "museo-300-italic": ['"MuseoSansW01-300Italic"', "sans-serif"],
      "museo-500": ['"Museo Sans W01_500"', "sans-serif"],
      "museo-700": ['"Museo Sans W01_700"', "sans-serif"],
      "museo-900": ['"Museo Sans W01_900"', "sans-serif"],
    },
  },
  variants: {
    extend: {},
    display: [
      "children",
      "children-first",
      "children-last",
      "children-odd",
      "children-even",
      "children-not-first",
      "children-not-last",
      "children-hover",
      "hover",
      "children-focus",
      "focus",
      "children-focus-within",
      "focus-within",
      "children-active",
      "active",
      "children-visited",
      "visited",
      "children-disabled",
      "disabled",
      "responsive",
    ],
    margin: ["responsive", "direction"],
    padding: ["responsive", "direction"],
    fontFamily: ['responsive', "direction"],
    backgroundColor: [
      "children",
      "responsive",
      "dark",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
    ],
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("tailwindcss-dir")(),
    require("tailwindcss-children"),
  ],
  corePlugins: {
    float: false,
  },
};
