export const imageStyles = [
    {
        name: "decoupled_image_424_238",
        width: 424,
        height: 238,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_640_360",
        width: 640,
        height: 360,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_840_840",
        width: 840,
        height: 840,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1280_840",
        width: 1280,
        height: 840,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1280_720",
        width: 1280,
        height: 720,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_100_100",
        width: 100,
        height: 100,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_459_259",
        width: 459,
        height: 259,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_272_180",
        width: 272,
        height: 180,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_360_239",
        width: 360,
        height: 239,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_300_199",
        width: 300,
        height: 199,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_419_278",
        width: 419,
        height: 278,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_424_281",
        width: 424,
        height: 281,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_273_173",
        width: 273,
        height: 173,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_480_314",
        width: 480,
        height: 314,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_768_503",
        width: 768,
        height: 503,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_675_442",
        width: 675,
        height: 442,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_480_311",
        width: 480,
        height: 311,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_370_239",
        width: 370,
        height: 239,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_560_363",
        width: 560,
        height: 363,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1200_520",
        width: 1200,
        height: 520,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1200_675",
        width: 1200,
        height: 675,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_480_208",
        width: 480,
        height: 208,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_768_333",
        width: 768,
        height: 333,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_2300_520",
        width: 2300,
        height: 520,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_375_155",
        width: 375,
        height: 155,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_768_318",
        width: 768,
        height: 318,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1000_414",
        width: 1000,
        height: 414,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1577_662",
        width: 1577,
        height: 662,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_390_567",
        width: 390,
        height: 567,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_400_479",
        width: 400,
        height: 479,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_434_520",
        width: 434,
        height: 520,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_633_632",
        width: 633,
        height: 632,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_588_587",
        width: 588,
        height: 587,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_550_549",
        width: 550,
        height: 549,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_1600_400",
        width: 1680,
        height: 400,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_359_235",
        width: 359,
        height: 235,
        operation: "scale_crop",
    },
    {
        name: "decoupled_image_546_358",
        width: 546,
        height: 358,
        operation: "scale_crop",
    }
];
